namespace EnvVarManager.Core;

public static class KnownApiKeyCatalog
{
    public static IReadOnlyList<KnownApiKeyDefinition> DefaultDefinitions { get; } =
    [
        new("OPENAI_API_KEY", "OpenAI", "OpenAI 官方 API Key", "LLM"),
        new("OPENAI_BASE_URL", "OpenAI Base URL", "OpenAI 兼容接口地址，可选", "LLM"),
        new("ANTHROPIC_API_KEY", "Anthropic", "Claude API Key", "LLM"),
        new("GEMINI_API_KEY", "Gemini", "Google Gemini API Key", "LLM"),
        new("GOOGLE_API_KEY", "Google API", "Google AI 或其他 Google API Key", "LLM"),
        new("DASHSCOPE_API_KEY", "DashScope / 百炼", "阿里云百炼 / 通义千问 API Key", "CN LLM"),
        new("MODELSCOPE_API_TOKEN", "ModelScope API Token", "ModelScope 魔搭 API Token", "CN LLM"),
        new("MODELSCOPE_SDK_TOKEN", "ModelScope SDK Token", "ModelScope SDK Token", "CN LLM"),
        new("DEEPSEEK_API_KEY", "DeepSeek", "DeepSeek API Key", "CN LLM"),
        new("MOONSHOT_API_KEY", "Moonshot / Kimi", "Moonshot AI / Kimi API Key", "CN LLM"),
        new("ZAI_API_KEY", "Z.ai / 智谱", "智谱 AI 新版官方 SDK API Key", "CN LLM"),
        new("ZHIPUAI_API_KEY", "ZhipuAI", "智谱 AI API Key，常见 SDK / LangChain 变量名", "CN LLM"),
        new("Z_AI_API_KEY", "Z.ai MCP", "智谱 / Z.ai MCP API Key", "CN LLM"),
        new("ZHIPU_API_KEY", "Zhipu", "智谱 AI 兼容变量名", "CN LLM"),
        new("QIANFAN_OPENAI_API_KEY", "Qianfan OpenAI", "百度千帆 OpenAI 兼容 API Key", "CN LLM"),
        new("QIANFAN_ACCESS_KEY", "Qianfan Access Key", "百度千帆 SDK Access Key", "CN LLM"),
        new("QIANFAN_SECRET_KEY", "Qianfan Secret Key", "百度千帆 SDK Secret Key", "CN LLM"),
        new("QIANFAN_AK", "Qianfan AK", "百度千帆 AK 兼容变量名", "CN LLM"),
        new("QIANFAN_SK", "Qianfan SK", "百度千帆 SK 兼容变量名", "CN LLM"),
        new("QIANFAN_API_KEY", "Qianfan API Key", "百度千帆 v2 / OpenAI 兼容 API Key", "CN LLM"),
        new("ARK_API_KEY", "Volcengine Ark", "火山方舟 / 豆包 API Key", "CN LLM"),
        new("VOLC_ACCESSKEY", "Volcengine AccessKey", "火山引擎 AccessKey ID", "CN Cloud"),
        new("VOLC_SECRETKEY", "Volcengine SecretKey", "火山引擎 Secret Access Key", "CN Cloud"),
        new("VOLCENGINE_ACCESS_KEY", "Volcengine Access Key", "火山引擎 Access Key", "CN Cloud"),
        new("VOLCENGINE_SECRET_KEY", "Volcengine Secret Key", "火山引擎 Secret Key", "CN Cloud"),
        new("VOLCENGINE_ACCESS_KEY_SECRET", "Volcengine AK Secret", "火山引擎 AccessKey Secret", "CN Cloud"),
        new("HUNYUAN_API_KEY", "Tencent Hunyuan", "腾讯混元 OpenAI 兼容 API Key", "CN LLM"),
        new("TENCENTCLOUD_SECRET_ID", "TencentCloud SecretId", "腾讯云 API SecretId", "CN Cloud"),
        new("TENCENTCLOUD_SECRET_KEY", "TencentCloud SecretKey", "腾讯云 API SecretKey", "CN Cloud"),
        new("MINIMAX_API_KEY", "MiniMax", "MiniMax API Key", "CN LLM"),
        new("BAICHUAN_API_KEY", "Baichuan", "百川智能 API Key", "CN LLM"),
        new("YI_API_KEY", "01.AI / Yi", "零一万物 Yi API Key", "CN LLM"),
        new("STEP_API_KEY", "StepFun", "阶跃星辰 StepFun API Key", "CN LLM"),
        new("SENSENOVA_ACCESS_KEY_ID", "SenseNova AK", "商汤日日新 Access Key ID", "CN LLM"),
        new("SENSENOVA_SECRET_ACCESS_KEY", "SenseNova SK", "商汤日日新 Secret Access Key", "CN LLM"),
        new("SENSENOVA_API_KEY", "SenseNova API Key", "商汤日日新 OpenAI 兼容 API Key", "CN LLM"),
        new("SILICONFLOW_API_KEY", "SiliconFlow", "硅基流动 SiliconFlow API Key", "CN LLM"),
        new("OPENROUTER_API_KEY", "OpenRouter", "OpenRouter API Key", "LLM"),
        new("GROQ_API_KEY", "Groq", "Groq API Key", "LLM"),
        new("MISTRAL_API_KEY", "Mistral", "Mistral API Key", "LLM"),
        new("COHERE_API_KEY", "Cohere", "Cohere API Key", "LLM"),
        new("PERPLEXITY_API_KEY", "Perplexity", "Perplexity API Key", "LLM"),
        new("XAI_API_KEY", "xAI", "xAI API Key", "LLM"),
        new("AZURE_OPENAI_API_KEY", "Azure OpenAI", "Azure OpenAI API Key", "Azure"),
        new("AZURE_OPENAI_ENDPOINT", "Azure Endpoint", "Azure OpenAI Endpoint", "Azure"),
        new("GITHUB_TOKEN", "GitHub Token", "GitHub Personal Access Token", "Dev"),
        new("HF_TOKEN", "Hugging Face", "Hugging Face Token", "Dev"),
        new("LANGSMITH_API_KEY", "LangSmith", "LangSmith API Key", "Observability"),
        new("TAVILY_API_KEY", "Tavily", "Tavily Search API Key", "Search"),
        new("SERPAPI_API_KEY", "SerpApi", "SerpApi API Key", "Search"),
        new("FIRECRAWL_API_KEY", "Firecrawl", "Firecrawl API Key", "Search"),
    ];
}
